### ISSUE TITLE
How to define an Interfaces?

### ISSUE THREAD

**Issue by mictian** [cancerberoSgx/short-jsdoc#7]
I searched the entire repo an the only place where I found some mention to interfaces was in the TODO.md. 
It is currently possible to define/document an interface. If it is the case, how?
If not, is there any kind of roadmap to it?

Thanks in advance,
Mictian

**Comment by cancerberoSgx** [comment]
I'm leaving this issue opened because this topic is interesting. I wonder why would you need @interface explicitly and can't use just @class ?

**Comment by mictian** [comment]
I think the main reason is to distinguish different semantics.
Certain module can expect a particular interface but does not necessarily implement it.
If you use "@class" I expect at least an (abstract or concrete) implementation of that class.

What do you think?

Thanks,
Mictian

**Comment by cancerberoSgx** [comment]
This was a very good idea. Is implemented and documented in the guide http://cancerberosgx.github.io/short-jsdoc/doc/guide/index.html#interface
