### ISSUE TITLE
Question: Why is short-jsdoc limited to only OOP?

### ISSUE THREAD

**Issue by mictian** [cancerberoSgx/short-jsdoc#8]
Hi,
I think this project is really awesome!, but I would like to understand why it is limited to Object Oriented Programming. Specially when JavaScript is more functional than OOP.
In JavaScritp (leaving aside the ugly new ES6 _class_ keyword) there is not way to create a class without doing a function. The global Object variable is indeed a function, etc. etc.

I found it hard to document part of my code using only OOP. For example when an interface is just a particular function's signature (not at class nor an object just a function).

Thanks in advance,
Mictian

**Comment by cancerberoSgx** [comment]
I'm accepting this issue as an enhancement. I agree with you, with the exception that the es6 class keyword is ugly :P

I guess that just supporting a functions associated with a module is enough ? Something like: 

```
@module foo 
@function bar some desc
@param {Type1} p1 some desc
@return {Type2} some desc
````

Or do you think global functions should not be associated with any module or to another entity ?

**Comment by mictian** [comment]
I think that could work pretty well.

I assume based on your comment that after that definition I would be able to use _bar_ as any other type, right? I mean, doing something like:

```js
//@exports {bar} 
module.exports = function () {/*...*/};

//@function returnsAnotherFunction
//@param {String} param1
//@return {foo}
function returnsAnotherFunction (param1) {
   return function (){};
}
```

Thanks for you fast replay!
Mictian

**Comment by cancerberoSgx** [comment]
short-jsdoc now supports functions and you can use them as types: http://cancerberosgx.github.io/short-jsdoc/doc/guide/#annotation-function

So I'm closing this, thanks! :)
